name: Build and Test

on:
  push:
    branches: [main]
    paths: ['Light.SharedCore/**', 'Light.SharedCore.Tests/**', 'build-and-test.yml']
  pull_request:
    branches: [main]
    paths: ['Light.SharedCore/**', 'Light.SharedCore.Tests/**', 'build-and-test.yml']

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./Light.SharedCore.slnx
    - name: Build
      run: dotnet build ./Light.SharedCore.slnx -c Release --no-restore
    - name: Test
      run: dotnet test ./Light.SharedCore.Tests/Light.SharedCore.Tests.csproj -c Release --no-build --verbosity normal
