name: Release to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dotnetVersion:
        description: "The version of .NET to use"
        required: false
        default: "9.0.x"

jobs:
  release-to-nuget:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ github.event.inputs.dotnetVersion || '9.0.x' }}
      - name: Prepare SNK file
        env:
          LIGHT_SHAREDCORE_SNK: ${{ secrets.LIGHT_SHAREDCORE_SNK }}
        run: |
          echo $LIGHT_SHAREDCORE_SNK | base64 --decode > ./Code/Light.SharedCore/Light.SharedCore.snk
      - name: Create NuGet packages
        run: dotnet pack ./Code/Light.SharedCore/Light.SharedCore.csproj -c Release /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Light.SharedCore.snk /p:ContinuousIntegrationBuild=true
      - name: Delete SNK file
        run: rm ./Code/Light.SharedCore/Light.SharedCore.snk
      - name: Push nupkg package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./Code/Light.SharedCore/bin/Release/Light.SharedCore.*.nupkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
